version: "3.7"
services:
  react-server:
    build:
      context: frontend # buildea el dockerfile presente en el dir frontend
    restart: always
    links: 
      - postgres-server
    ports:
      - "3000:3000" # escucha en puerto 3000
  postgres-server:
    image: postgres  # pull de postgres desde docker hub
    links: 
      - postgres-server
    restart: always
    ports:
      - '5432:5432'
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # setea la pass de postgres desde env de entorno
      POSTGRES_DB: ${POSTGRES_DATABASE} # setea database name
    cap_add:
      - SYS_NICE 
    volumes:
      - ${POSTGRES_DATA_DIR-./data/postgres}:/var/lib/postgresql  # monta un volumenn local para la data
  phpmyadmin:
    build:
      context: backend # buildea desde el dir backend
    links: 
      - postgres-server # depende de postgres-server
    restart: always
    environment: # setea las variables de entorno y expone el puerto 8000
      DJANGO_ENV: environment
      DJANGO_DEBUG: "0"
      SECRET_KEY: )y^+8k$7c8l@wi-06^kl#4j=&0%*x_i4vrrnqb0u9r7uf8^04j
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_ADMIN_USER: admin
      DJANGO_ADMIN_EMAIL: "admin@example.com"
      DB_ENGINE: "django.db.backends.postgresql_psycopg2"
      DB_HOST: postgres-server
      DB_PORT: "5432"
      DB_NAME: predictiondb
      DB_USER: postgres
      DATABASE: postgres
      DB_PASS: ${POSTGRES_PASSWORD}
    ports:
      - '8000:8000'
